export default {
  AUTH0: {
    DOMAIN: process.env.AUTH0_DOMAIN,
    CLIENT_ID: process.env.AUTH0_CLIENT_ID,
    CLIENT_SECRET: process.env.AUTH0_CLIENT_SECRET,
    COOKIE_SECRET: process.env.AUTH0_COOKIE_SECRET,
    AUDIENCE: process.env.AUTH0_AUDIENCE,
    CALLBACK_URL: process.env.AUTH0_CALLBACK_URL,
    LOGOUT_REDIRECT: process.env.AUTH0_LOGOUT_REDIRECT
  },
  CRYPTO: {
    SECRET_KEY: process.env.CRYPTO_SECRET_KEY
  },
  CONTENTFUL: {
    SPACE_ID: process.env.CONTENTFUL_SPACE_ID,
    MANAGEMENT_ACCESS_TOKEN: process.env.CONTENTFUL_MANAGEMENT_ACCESS_TOKEN,
    DELIVERY_ACCESS_TOKEN: process.env.CONTENTFUL_DELIVERY_ACCESS_TOKEN,
    PREVIEW_ACCESS_TOKEN: process.env.CONTENTFUL_PREVIEW_ACCESS_TOKEN
  }
}