name: Serok
on: [push]

jobs:
  serok-code:
    runs-on: ubuntu-latest
    container:
      image: rsneh/serok:latest
    steps:
        - uses: actions/checkout@v2
        - name: Start Serok
          uses: docker://rsneh/serok:latest
          env:
            SECODE_TOKEN: ${{ secrets.SECODE_TOKEN }}
            ACTOR: ${{ github.actor }}
            REPOSITORY: ${{ github.repository }}
