name: Serok
on: [push]

jobs:
  serok-code:
    runs-on: ubuntu-latest
    container:
      image: rsneh/serok:latest
      env:
        WORKSPACE: ${GITHUB_WORKSPACE}
      volumes:
        - ${GITHUB_WORKSPACE}:/app
    steps:
         - name: Log the node version
           run: |
             node -v
             cat /etc/os-release  
