name: Serok
on: [push]

jobs:
  serok-code:
    runs-on: ubuntu-latest
    container:
      image: rsneh/serok:latest
      env:
        WORKSPACE: ${GITHUB_WORKSPACE}
      volumes:
        - ${GITHUB_WORKSPACE}:/app
