name: Serok
on: [push]

jobs:
  serok-code:
    runs-on: ubuntu-latest
    container:
      image: rsneh/serok:latest
      env:
        WORKSPACE: ${{ github.workspace }}
      volumes:
        - ${{ github.workspace }}:/app
    steps:
        - name: Log the node version
          run: |
            node -v
            cat /etc/os-release  
        - name: Start Serok
          uses: docker://rsneh/serok:latest

