name: Serok
on: [push]

jobs:
  serok-code:
    runs-on: ubuntu-latest
    container:
      image: rsneh/serok:latest
      env:
        ACTOR: ${{ github.actor }}
        REPOSITORY: ${{ github.repository }}
        SECODE_TOKEN: ${{ secrets.SECODE_TOKEN }}
    steps:
        - run: echo "$SECODE_TOKEN. Repo is $REPOSITORY!"
#         - uses: actions/checkout@v2
#         - name: Start Serok
#           uses: docker://rsneh/serok:latest

